openapi: 3.0.0
info:
  title: Atomberg Home Public APIs
  description: |
    Welcome to the Developer Console of the Atomberg Home Smart Platform (referred to as Phoenix).
    
    This webpage documents the APIs that allow you to control your Atomberg smart fans programmatically.

    Now the Phoenix platform is your playground!  
    
    
    *Want to set a custom sleep mode routine for your fan? Go for it.*  
    
    *Want to trigger your fan based on inputs from other appliances or sensors? It's possible now.*  
    
    *Want to get your hands dirty with a smart home automation system? We are glad to provide you the first experience.*  
    

    We can't wait to see all the interesting ideas that you come up with. In order to access these APIs, you need


    1. One or more Atomberg smart fans connected to the Atomberg Home app. Check out our range of smart fans [here](https://atomberg.com/landing/smartfans).
    
    2. API Key

    3. Refresh token: This is used to generate the access token that is further
    used for authenticating other API calls
        

    Both the API Key and Refresh token can be generated by enabling the developer options in the
    Atomberg Home app. Please note that you only get access to control Wi-Fi
    enabled smart devices added to the account used for generating the above
    credentials in the Atomberg Home app. The quota limitations for each API Key
    is as follows:


    1. Daily: 100 API calls/day

    2. Throttle: 5 API calls/second
    
    # Home Assistant Integration
    
    For users looking to use the public API for Home Assistant, please check out [this integration](https://github.com/dasshubham762/atomberg-integration) by one of our users.
        

    # Quickstart


    ## Step 1


    Enable Developer Mode in the Atomberg Home app. This will generate the API
    Key and refresh token required for further API operations. Store them
    securely. The API key needs to be passed into the x-api-key header in all
    API calls. The refresh token needs to be used only in the authorization
    header of the 'Get Access Token' API.


    <img
    src="https://content.pstmn.io/0d5fdc26-b917-435f-943d-f8dad38f3c51/U2NyZWVuX1JlY29yZGluZ18yMDI0MDMwNl8yMzU5MjUtZXpnaWYuY29tLXZpZGVvLXRvLWdpZi1jb252ZXJ0ZXIuZ2lm" height = "500">


    ## Step 2


    Use the refresh token in the Authorization Header of the 'Get Access Token'
    API and get the Access token for use in the subsequent APIs. This token has
    an expiry duration of 24 hours.


    ## Step 3


    Using the obtained Access Token in the Authorization Header of the 'Get List
    of Devices' API. This API will return information of all the devices in your
    account. Note down the device_ids of the devices of interest.


    ## Step 4


    Use the device_id to either get the state of a device (using the 'Get Device
    State' API), or send command to any device (using the 'Send Command' API)


    ---

    * For any queries, please contact app@atomberg.com
    * Please ensure that your developer credentials are stored securely
    * If you suspect that your developer credentials have been leaked, please disable the Developer Mode immediately from the Atomberg Home app</em>
  version: 1.0.0
servers:
  - url: https://api.developer.atomberg-iot.com
components:
  securitySchemes:
    apikeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: x-api-key
tags:
  - name: Get Access
    description: >-
      The API here allows you to generate an access token to be used for device
      interactions. The refresh token and the API Key obtained when enabling the
      developer mode on the Atomberg Home app are required headers for the 'Get
      Access Token' request.
  - name: Device Interactions
    description: The requests here allow you to interact with the devices.
paths:
  /v1/get_access_token:
    get:
      tags:
        - Get Access
      summary: Get Access Token
      description: >-
        Use this request to fetch an access token for further API calls. The
        generated access token has an expiry of 24 hours. Please note that the
        access_token needs to be regenerated every time a device is added to or
        removed from your Atomberg Home account.
      security:
        - apikeyAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImI0MDM...
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '2865'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Tue, 05 Mar 2024 13:22:16 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: 70dcb490-cfbd-4b82-9223-a70bf9514332
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: UKFlFHd1hcwEDMg=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: >-
                  Root=1-65e71c86-34bcda593b2d472b4696e50f;Parent=3b5e5a6f8617b80e;Sampled=0;lineage=7c819c3a:0
            X-Cache:
              schema:
                type: string
                example: Miss from cloudfront
            Via:
              schema:
                type: string
                example: >-
                  1.1 4f07bcbac1ca576cf7ef48afd8670a08.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: PNQ50-P2
            X-Amz-Cf-Id:
              schema:
                type: string
                example: hsetXTC3WsGNRgzNrZXMhOK5hLRylabHiaKnxK2slyCY8oF1MeP7pw==
          content:
            application/json:
              schema:
                type: object
              example:
                status: Success
                message:
                  access_token: >-
                    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImI0MDM4OTE4LWJmOWYtNDNjMC1iNWQ4LTg3ZGU2ZmNlYWQwNiIsInR5cGUiOiJhY2Nlc3MiLCJpc3MiOiJkZXZlbG9wZXIuYXRvbWJlcmctaW90LmNvbSIsImRldmljZV9pbmZvIjoiWEdsVjZzMWE3T...
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json+hal
            Content-Length:
              schema:
                type: integer
                example: '111'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Tue, 05 Mar 2024 17:57:24 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: c998dbb3-6e07-4c82-9d7c-34430a27d7b0
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: UKt4fHvcBcwEeQw=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: >-
                  Root=1-65e75d02-6154a2ea6f6b983243c83975;Parent=73ef349c2808e2cf;Sampled=0;lineage=7c819c3a:0
            X-Cache:
              schema:
                type: string
                example: Error from cloudfront
            Via:
              schema:
                type: string
                example: >-
                  1.1 42969bd44191f50c490e6b48fade4d40.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: PNQ50-P2
            X-Amz-Cf-Id:
              schema:
                type: string
                example: 2wjeUQe35MPGzFd28f9uLbmQ3tiiQ5nRscZgXefRVoNPPNEdBpnvLg==
          content:
            application/json:
              schema:
                type: object
              example:
                status: Error
                message: >-
                  [401] Authorization error JwtParseError: Signature
                  verification failed
  /v1/get_list_of_devices:
    get:
      tags:
        - Device Interactions
      summary: Get List of Devices
      description: >-
        This API gives you a list of all the devices that are present in your
        Atomberg Home app account. Please note that every time a device is added
        or removed, the access_token needs to be generated again after each
        device addition and removal. The key parameter to extract is the
        device_id for your fans. This device_id will be used for further API
        commands.
      security:
        - apikeyAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImI0MDM4OTE4LWJmOWYtNDNjMC1iNWQ4LTg3ZGU2ZmNlYWQwNiIsInR5cGUiOiJhY2Nlc3MiLCJpc3MiOiJkZXZlbG9wZXIuYXRvbWJlcmctaW90LmNvbSIsImRldmljZV9pbmZvIjoiWEdsVjZzMWE3T...
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '1338'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Tue, 05 Mar 2024 13:22:38 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: b2f0a7a5-b800-4bdd-9244-20e6e923ca4d
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: UKFomFlqBcwEIvA=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: >-
                  Root=1-65e71c9d-45389dc33db9b550071bb079;Parent=7c18a90afdc5b0a9;Sampled=0;lineage=0baaf517:0
            X-Cache:
              schema:
                type: string
                example: Miss from cloudfront
            Via:
              schema:
                type: string
                example: >-
                  1.1 4f07bcbac1ca576cf7ef48afd8670a08.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: PNQ50-P2
            X-Amz-Cf-Id:
              schema:
                type: string
                example: dFeFtjk7QLVifTP6Ev9m-jIcSQXR1Cnb1v8TEPyL_rx_dUDOYK4YtQ==
          content:
            application/json:
              schema:
                type: object
              example:
                status: Success
                message:
                  devices_list:
                    - metadata:
                        ssid: IOT Extender
                      device_id: 68672590641c
                      color: Snow White
                      series: K1
                      model: erica
                      room: Living Room
                      name: Erica fan
                    - metadata:
                        ssid: JioFiber_ 2.4G
                      device_id: 6867258b9d78
                      color: Marble White
                      series: I1
                      model: aris
                      room: Living Room
                      name: Atom Fan
                    - metadata:
                        ssid: Better_Together
                      device_id: a0764e5aee98
                      color: Golden Oakwood
                      series: R1
                      model: renesa+
                      room: Living Room
                      name: Smart Fan AAAAAAVBBBBB
                    - metadata:
                        ssid: Warhate@HOME
                      device_id: a0764e2373b4
                      color: Marble White
                      series: I1
                      model: aris
                      room: Living Room
                      name: Aris Fan
                    - metadata:
                        ssid: Better_Together
                      device_id: 84fce6285b28
                      color: White and Black
                      series: R1
                      model: renesa
                      room: Living Room
                      name: Renesa Fan
                    - metadata:
                        ssid: Better_Together
                      device_id: 6867258f83d0
                      color: Marble White
                      series: I1
                      model: aris
                      room: Living Room
                      name: Aris Fan
                    - metadata:
                        ssid: Better_Together
                      device_id: 64e833ee5244
                      color: Pearl White
                      series: R1
                      model: renesa+
                      room: Living Room
                      name: Renes3a Fan
                    - metadata:
                        ssid: Better_Together
                      device_id: a0764ee4210c
                      color: Dark Teakwood
                      series: I1
                      model: aris
                      room: Living Room
                      name: Aris Fan
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json+hal
            Content-Length:
              schema:
                type: integer
                example: '96'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Tue, 05 Mar 2024 17:47:27 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: 8f4819f0-c18a-4ab5-8d3f-74abc3807bd6
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: UKsbOEaIBcwEQMg=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: >-
                  Root=1-65e75aad-630e25c475a9cd7421d7aa46;Parent=53bc7d66e1b77b90;Sampled=0;lineage=0baaf517:0
            X-Cache:
              schema:
                type: string
                example: Error from cloudfront
            Via:
              schema:
                type: string
                example: >-
                  1.1 42969bd44191f50c490e6b48fade4d40.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: PNQ50-P2
            X-Amz-Cf-Id:
              schema:
                type: string
                example: vkT4UJ29Zmrl8a0omPkHVMqGZTxaoR42lj8_F76QcohHD5JxcwvH2Q==
          content:
            application/json:
              schema:
                type: object
              example:
                status: Error
                message: '[401] Authorization error JwtParseError: Jwt is expired'
        '429':
          description: Too Many Requests
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '28'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Tue, 05 Mar 2024 17:53:21 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: 2feeb6ad-ac1d-4d21-9415-5739a25c24d9
            x-amzn-ErrorType:
              schema:
                type: string
                example: LimitExceededException
            x-amz-apigw-id:
              schema:
                type: string
                example: UKtSuEPzhcwENVQ=
            X-Cache:
              schema:
                type: string
                example: Error from cloudfront
            Via:
              schema:
                type: string
                example: >-
                  1.1 42969bd44191f50c490e6b48fade4d40.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: PNQ50-P2
            X-Amz-Cf-Id:
              schema:
                type: string
                example: i01_HWepeGcnd8bqOJL9hEJZPY1ojWRRO6JA4KORfqNVQUUdYA29GA==
          content:
            application/json:
              schema:
                type: object
              example:
                message: Limit Exceeded
  /v1/send_command:
    post:
      tags:
        - Device Interactions
      summary: Send Command
      description: >-
        Send a command to a specific device. Requires the device_id of the
        device that you want to control (it can be obtained from the 'Get List
        of Devices' API). The complete list of commands is:


        | Command | Description | JSON | Accepted values for val | Comments |

        | --- | --- | --- | --- | --- | 

        | Power | Turn the fan ON or OFF | {"power":val} | true, false |  | 

        | Speed Absolute | Set the speed of the fan to an absolute value |
        {"speed":val} | 1,2,3,4,5,6 |  | 

        | Speed Relative | Increase/decrease speed of the fan |
        {"speedDelta":val} | 1,2,3,4,5,-1,-2,-3,-4,-5 |  | 

        | Sleep mode | Enable or disable sleep mode | {"sleep":val} | true,
        false |  | 

        | Timer | Set timer | {"timer":val} | 0,1,2,3,4 | 0: Turn off timer 
        <br>1: Set timer for 1 hours  <br>2: Set timer for 2 hours  <br>3: Set
        timer for 3 hours  <br>4: Set timer for 6 hours | 

        | Lights ON/OFF | Turn the light ON or OFF | {"led":val} | true, false |
        For Aris Starlight, it will set the fan light at the last known color or
        brightness values | 

        | Brightness Absolute | Set the brightness of the fan to an absolute
        value | {"brightness":val} | 10 to 100 | Percentage brightness | 

        | Brightness Delta | Increase/decrease brightness of the fan |
        {"brightnessDelta":val} | \-90 to +90 | Percentage brightness | 

        | Color | Change the color of the light | {"light_mode":val} |
        "warm","cool","daylight" |  | 
        
        
        The list of supported models and the corresponding command mapping is given below:
        
        | Model          | Series | Power | Speed | Sleep | Timer | LED ON/OFF | Brightness Change | Color Change | 
        
        | -------------- | ------ | ----- | ----- | ----- | ----- | ---------- | ----------------- | ------------ | 
        
        | Renesa         | R1     | Yes   | Yes   | Yes   | Yes   | Yes        | No                | No           | 

        | Renesa Halo    | R1/R2  | Yes   | Yes   | Yes   | Yes   | Yes        | No                | No           | 
        
        | Renesa+        | R1     | Yes   | Yes   | Yes   | Yes   | Yes        | No                | No           | 
        
        | Studio+        | R1     | Yes   | Yes   | Yes   | Yes   | Yes        | No                | No           | 
        
        | Erica          | K1     | Yes   | Yes   | Yes   | Yes   | Yes        | No                | No           | 
        
        | Aris Starlight | I1     | Yes   | Yes   | Yes   | Yes   | Yes        | Yes               | Yes          | 
        
        | Aris           | I2     | Yes   | Yes   | Yes   | Yes   | Yes        | No                | No           | 
        
        | Aris Contour   | M1     | Yes   | Yes   | Yes   | Yes   | Yes        | Yes               | No           |

        | Renesa Elite   | S1     | Yes   | Yes   | Yes   | Yes   | Yes        | Yes               | No           |

        | Studio Nexus   | S1     | Yes   | Yes   | Yes   | Yes   | Yes        | Yes               | No           |

        # Sending the command locally
        
        You can control the fans locally over UDP, without having to rely on the cloud API. The steps involved are as follows:
        
        ## Step 1: Check if the device is available on the local network. 
        
        Each device sends a beacon packet over UDP every one second on port 5625. This beacon packet contains the MAC address of the device, followed by the series (mac_series). You can have a background service that listens for the beacon packets and stores the mapping of MAC against the IP address.

        A sample implementation in Python is given below:

        ```plaintext
        
        import socket
        
        import threading
        
        import time


        # Define the UDP port to listen on
        
        UDP_IP = "0.0.0.0"  # Listen on all available interfaces
        
        UDP_PORT = 5625
        
        BUFFER_SIZE = 4096  # Adjust as needed
        
        TIMEOUT = 2  # seconds


        available_devices = {}
        
        lock = threading.Lock()


        def cleanup_inactive_devices():
            while True:
                now = time.time()
                with lock:
                    inactive_devices = [mac for mac, (ip, ts) in available_devices.items() if now - ts > TIMEOUT]
                    for mac in inactive_devices:
                        print(f"Removing inactive device: {mac}")
                        del available_devices[mac]
                time.sleep(1) 

        def main():
            # Create a UDP socket
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

            # Bind the socket to the IP and port
            sock.bind((UDP_IP, UDP_PORT))
            print(f"Listening for UDP packets on port {UDP_PORT}...")

            # Start background cleanup thread
            threading.Thread(target=cleanup_inactive_devices, daemon=True).start()

            try:
                while True:
                    data, addr = sock.recvfrom(BUFFER_SIZE)  # Receive packet
                    ip, port = addr
                    content = data.decode(errors='replace')
                    if len(content) <= 15:
                        print("Beacon packet received")
                        mac = content[:12]
                        with lock:
                            available_devices[mac] = (ip,time.time())
                    print(f"Received packet from {ip}:{port}")
                    print(f"available device data: {available_devices}")
                    # You can also store this in a file or database if needed
            except KeyboardInterrupt:
                print("\nStopped by user.")
            finally:
                sock.close()

        if __name__ == "__main__":
            main()
        ```

        ## Step 2: Send the command for the device

        If you have identified the MAC address of the device to which you wish to send the command, you can use the command JSONs (described above) to send the command to the intended device. Please note that the command should be sent over port 5600.

        An example implementation in Python is given below:

        ```plaintext
        
        import json
        
        import socket 


        TARGET_IP = "192.168.29.233"
        
        TARGET_PORT = 5600


        # JSON command to send
        
        command = {
            "led":False
        }


        # Convert to JSON string and encode to bytes
        
        message = json.dumps(command).encode('utf-8')


        # Create UDP socket
        
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)


        # Send the message
        
        sock.sendto(message, (TARGET_IP, TARGET_PORT))
        
        print(f"Sent JSON command to {TARGET_IP}:{TARGET_PORT}")


        # Close the socket
        
        sock.close()
        
        ```

      # Cloud based implementation

      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                device_id: 6867258b9d78
                command:
                  timer: 0
      security:
        - apikeyAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImI0MDM4OTE4LWJmOWYtNDNjMC1iNWQ4LTg3ZGU2ZmNlYWQwNiIsInR5cGUiOiJhY2Nlc3MiLCJpc3MiOiJkZXZlbG9wZXIuYXRvbWJlcmctaW90LmNvbSIsImRldmljZV9pbmZvIjoiWEdsVjZzMWE3T...
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '58'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Tue, 05 Mar 2024 13:22:49 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: a78d9357-90e9-447d-9837-4cff49bd6e36
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: UKFqWGHghcwEXkQ=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: >-
                  Root=1-65e71ca8-22b239a6288b851163302c19;Parent=5ef1ed90a2ede914;Sampled=0;lineage=9e25b377:0
            X-Cache:
              schema:
                type: string
                example: Miss from cloudfront
            Via:
              schema:
                type: string
                example: >-
                  1.1 4f07bcbac1ca576cf7ef48afd8670a08.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: PNQ50-P2
            X-Amz-Cf-Id:
              schema:
                type: string
                example: CzODnyyNJsbPLnos-Y7mgNWypWSTp3AnrdbkE0zu_I7jJjTSENYSeg==
          content:
            application/json:
              schema:
                type: object
              example:
                status: Success
                message: Message sent successfully
        '404':
          description: Not Found
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json+hal
            Content-Length:
              schema:
                type: integer
                example: '63'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Tue, 05 Mar 2024 17:49:12 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: edb81fff-4f24-4ae2-86f9-2defa9337df0
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: UKsr6HhsBcwEVpA=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: >-
                  Root=1-65e75b18-17f802070e01170716e4d13e;Parent=5043fbadd016d880;Sampled=0;lineage=9e25b377:0
            X-Cache:
              schema:
                type: string
                example: Error from cloudfront
            Via:
              schema:
                type: string
                example: >-
                  1.1 42969bd44191f50c490e6b48fade4d40.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: PNQ50-P2
            X-Amz-Cf-Id:
              schema:
                type: string
                example: cv-8AZ3mmPlZgZlkelfxiLrcVD-VfOL9t-GcP2FWXa8qmFeKqLI3RA==
          content:
            application/json:
              schema:
                type: object
              example:
                status: Error
                message: '[404] Device not found'
  /v1/get_device_state:
    get:
      tags:
        - Device Interactions
      summary: Get Device State
      description: |
        Get the last known state of the device.
        
        Some developers, especially those who keep querying the state of their fan(s) frequently, may soon hit the API limit with this API. For these developers, it is better to listen to the state of the fan(s) locally over UDP. If you would rather access the device state using an API rather than locally over UDP, skip the next section.
        
        ## Reading the state from the fan over UDP

        Once the fan receives any command and takes action, it updates its state over UDP on the broadcast port (5625). The message is received in the hex format, and needs to be converted to ASCII. For example, the message received may be 
        

        ```plaintext
        7b226465766963655f6964223a22613037363465356165653938222c226d6573736167655f6964223a2241636d42696a6d6f6d666e424a62486341222c2273746174655f737472696e67223a2232302c312c422c352c35302e30302c302c302c52312c323830322c312c34353134322c302c302c302c302c302e30302c302e30302c302c302c302c454e44227d
        ```
        

        When converted to ASCII, the state message reads

        ```json
        {
          "device_id":"a0764e5aee98",
          "message_id":"AcmBijmomfnBJbHcA",
          "state_string":"20,1,B,5,50.00,0,0,R1,2802,1,45142,0,0,0,0,0.00,0.00,0,0,0,END"
        }
        
        ```


        The message_id is a unique identifier for each message. This can help the system discard duplicates.

        The state_string contains the current state of the fan, apart from a lot of other debug fields. The current state (speed, power, light brightness, etc.) can be decoded from the first field of the state string itself (the first field is 20 in the above example). Its decoding logic is given below:

        ```plaintext
        var power = (0x10) & value > 0 ? true : false;
        var led = (0x20) & value > 0 ? true : false;
        var sleep = (0x80) & value > 0 ? true : false;
        var speed = (0x07) & value;
        var fanTimer = ((0x0F0000 & value) / 65536).round();
        var fanTimerElapsedMins = ((0xFF000000 & value) * 4 / 16777216).round();

        //Aris Starlight Specific
        var Brightness = (((0x7F00) & value) / 256).round();
        var Cool = ((0x08) & value) > 0 ? true : false;
        var Warm = ((0x8000) & value) > 0 ? true : false;

        If both Cool and Warm are true, then color is 'Daylight'
        ```
      security:
        - apikeyAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImI0MDM4OTE4LWJmOWYtNDNjMC1iNWQ4LTg3ZGU2ZmNlYWQwNiIsInR5cGUiOiJhY2Nlc3MiLCJpc3MiOiJkZXZlbG9wZXIuYXRvbWJlcmctaW90LmNvbSIsImRldmljZV9pbmZvIjoiWEdsVjZzMWE3T...
        - name: device_id
          in: query
          schema:
            type: string
          example: all
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '298'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Tue, 05 Mar 2024 13:23:03 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: 02f94790-8f78-4925-a09a-2368b825510d
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: UKFsKHlRBcwEUDw=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: >-
                  Root=1-65e71cb3-260425356a11d9bf5638931e;Parent=6a90ede290a952e4;Sampled=0;lineage=4f7703ff:0
            X-Cache:
              schema:
                type: string
                example: Miss from cloudfront
            Via:
              schema:
                type: string
                example: >-
                  1.1 4f07bcbac1ca576cf7ef48afd8670a08.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: PNQ50-P2
            X-Amz-Cf-Id:
              schema:
                type: string
                example: vCcLIEDwMK2hwVBZ7frhqaP_Hzjyi3XowHG9b8185ZTQZ1HXICiAlA==
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Single Device
                  value:
                    status: Success
                    message:
                      device_state:
                        - device_id: 6867258b9d78
                          power: false
                          last_recorded_speed: 4
                          sleep_mode: false
                          led: false
                          is_online: true
                          timer_hours: 1
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1709644969
                          last_recorded_brightness: 100
                          last_recorded_color: cool
                example-1:
                  summary: All Devices
                  value:
                    status: Success
                    message:
                      device_state:
                        - device_id: 68672590641c
                          power: false
                          last_recorded_speed: 5
                          sleep_mode: false
                          led: false
                          is_online: false
                          timer_hours: 0
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1707826542
                        - device_id: 6867258b9d78
                          power: true
                          last_recorded_speed: 5
                          sleep_mode: false
                          led: false
                          is_online: true
                          timer_hours: 0
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1709660239
                          last_recorded_brightness: 100
                          last_recorded_color: cool
                        - device_id: a0764e5aee98
                          power: false
                          last_recorded_speed: 6
                          sleep_mode: false
                          led: false
                          is_online: false
                          timer_hours: 0
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1708504004
                        - device_id: a0764e2373b4
                          power: true
                          last_recorded_speed: 3
                          sleep_mode: false
                          led: false
                          is_online: false
                          timer_hours: 0
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1700189094
                          last_recorded_brightness: 10
                          last_recorded_color: daylight
                        - device_id: 84fce6285b28
                          power: false
                          last_recorded_speed: 6
                          sleep_mode: false
                          led: false
                          is_online: false
                          timer_hours: 0
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1703827616
                        - device_id: 6867258f83d0
                          power: false
                          last_recorded_speed: 2
                          sleep_mode: false
                          led: false
                          is_online: true
                          timer_hours: 0
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1709640761
                          last_recorded_brightness: 10
                          last_recorded_color: cool
                        - device_id: 64e833ee5244
                          power: true
                          last_recorded_speed: 3
                          sleep_mode: false
                          led: true
                          is_online: true
                          timer_hours: 0
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1709636050
                        - device_id: a0764ee4210c
                          power: true
                          last_recorded_speed: 2
                          sleep_mode: false
                          led: false
                          is_online: false
                          timer_hours: 0
                          timer_time_elapsed_mins: 0
                          ts_epoch_seconds: 1709622411
                          last_recorded_brightness: 85
                          last_recorded_color: warm
